server:
  port: 8085
spring:
  application:
    name: admin-server
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      uri: ${CONFIG_URL:http://config:config-password@localhost:8888}
