spring:
  application:
    name: admin-server
  cloud:
    config:
      enabled: false
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  client:
    enabled: false
