services:
  postgres:
    container_name: microservices_db_java
    image: postgres:16.3
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default
      - java-microservices
  keycloak:
    container_name: microservices_keycloak
    image: quay.io/keycloak/keycloak:24.0
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./config/keycloak/import:/opt/keycloak/data/import
    ports:
      - ${KC_PORT:-8080}:8080
    networks:
      - default
      - java-microservices
    user: "${UID}:${GID}"
  victoria-metrics:
    container_name: microservices_victoria_metrics
    image: victoriametrics/victoria-metrics:latest
    ports:
      - ${VM_PORT:-8428}:8428
    volumes:
      - ./config/victoria-metrics/promscrape.yaml:/promscrape.yaml
    command:
      - '-promscrape.config=promscrape.yaml'
    networks:
      - default
      - java-microservices
  grafana:
    container_name: microservices_grafana
    image: grafana/grafana:latest
    ports:
      - ${GF_PORT:-3000}:3000
    volumes:
      - ./data/grafana/:/var/lib/grafana
    networks:
      - default
      - java-microservices
    user: "${UID}:${GID}"
  loki:
    container_name: microservices_loki
    image: grafana/loki:latest
    ports:
      - ${LOKI_PORT:-3100}:3100
    volumes:
      - ./data/loki/:/var/lib/loki
    user: "${UID}:${GID}"
    networks:
      - default
      - java-microservices
  tracing:
    container_name: microservices_tracing
    image: grafana/tempo:latest
    ports:
      - ${TRACING_TEMPO_PORT:-3200}:3200
      - ${TRACING_GRPC_PORT:-9095}:9095
      - ${TRACING_GRPC_TELEMETRY_PORT:-4317}:4317
      - ${TRACING_GRPC_TELEMETRY_HTTP_PORT:-4318}:4318
      - ${ZIPKIN_PORT:-9411}:9411
      - ${JAGGER_PORT:-14268}:14268
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
    command:
      - '-config.file=/etc/tempo.yaml'

volumes:
  pgdata:

networks:
  java-microservices:
    external: true
