spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
        routes:
          - id: employee-service-route
            uri: http://localhost:8080
            predicates:
              - Host=employee.api.microservices
server:
  port: 8086
  forward-headers-strategy: framework
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    enabled: false
