server:
  port: 8086
  forward-headers-strategy: framework
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      uri: ${CONFIG_URL:http://config:config-password@localhost:8888}
