server:
  port: 8080
logging:
  level:
    org.flywaydb: DEBUG
    sql: info
spring:
  cloud:
    config:
      enabled: false
  application:
    name: employee
  messages:
    encoding: UTF-8
    basename: messages
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:6432/postgres}
    username: postgres
    password: postgres
  flyway:
    schemas:
      - public
      - employee
    default-schema: employee
  jpa:
    show-sql: true
  boot:
    admin:
      client:
        enabled: true
        url: ${ADMIN_URL:http://localhost:8085}
        instance:
          name: employee-service
          service-host-type: ip
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    enabled: false
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8082/realms/java-microservices
#            user-name-attribute: preferred_username
#        registration:
#          employee-app:
#            provider: keycloak
#            client-id: employee-app
#            client-secret: 0JnXSRZPopcPVO3RFCodLMGevrRdQAJw
#            scope:
#              - openid
#              - edit_client
#              - view_client
#              - microprofile-jwt
#            authorization-grant-type: authorization_code
