server:
  port: 8080
  address: 127.0.0.1
logging:
  level:
    org.flywaydb: DEBUG
    sql: info
spring:
  application:
    name: employee
  messages:
    encoding: UTF-8
    basename: messages
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
  flyway:
    schemas:
      - public
      - employee
    default-schema: employee
  jpa:
    show-sql: true
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8085
        instance:
          name: employee-service
          service-host-type: ip
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8082/realms/java-microservices
#            user-name-attribute: preferred_username
#        registration:
#          employee-app:
#            provider: keycloak
#            client-id: employee-app
#            client-secret: 0JnXSRZPopcPVO3RFCodLMGevrRdQAJw
#            scope:
#              - openid
#              - edit_client
#              - view_client
#              - microprofile-jwt
#            authorization-grant-type: authorization_code

