server:
  port: 8761
spring:
  application:
    name: eureka-server
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: ${CONFIG_URL:http://config:config-password@localhost:8888}
